apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: swagger-ui
  name: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: swagger-ui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: swagger-ui
    spec:
      containers:
        - image: swaggerapi/swagger-ui
          name: swagger-ui
          env:
            - name: URLS
              value: '[ { url: ''http://localhost:3005/income/v3/api-docs'', name: ''Income''}, { url: ''http://localhost:3005/wallet/openapi'', name: ''Wallet''}, { url: ''http://localhost:3005/account/v3/api-docs'', name: ''Account''},  { url: ''http://localhost:3005/mq/v3/api-docs'', name: ''MQ''}, { url: ''http://localhost:3005/cm/v3/api-docs'', name: ''CM''}, ]'
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
